server:
  port: 8080

name: abc

#对象
person:
  name: 张三 #${name}
  age: 20
  #数组
  address:
    - 中国
    - 北京


#对象行内写法
person2: {name: zhangsan,age: 20}
#数组
address:
  - 中国
  - 上海

#数组行内写法
address1: {beijing,shanghai}

#纯量
msg1: 'hello \n world' #不会识别转义字符，会原样输出
msg2: "hello \n world" # 会识别转义字符


