---
server:
  port: 8081
spring:
  profiles:
    dev
---
server:
  port: 8082

spring:
  profiles:
    pro
---
server:
  port: 8083
spring:
 profiles:
    test

---
spring:
  profiles:
    active: pro


datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
  username: root
  password: root